import {PhonemeProfile} from "./vocabulary";
import {Constituent} from "./types";

export type LanguageProfile = {
    phonemes: PhonemeProfile;
    typicalSyllableStructures?: string[];
    typicalOrder?: Constituent[];
}

export const LanguageProfiles: Record<string, LanguageProfile> = {
    Turkic: {
        phonemes: {
            consonants: [
                { ipa: 'p',  glyph: 'p',  type: 'alveolar'    },
                { ipa: 'b',  glyph: 'b',  type: 'alveolar'    },
                { ipa: 't',  glyph: 't',  type: 'alveolar'    },
                { ipa: 'd',  glyph: 'd',  type: 'alveolar'    },
                { ipa: 'k',  glyph: 'k',  type: 'alveolar'    },
                { ipa: 'g',  glyph: 'g',  type: 'alveolar'    },
                { ipa: 'tʃ', glyph: 'ch', type: 'palatal'     },
                { ipa: 'dʒ', glyph: 'j',  type: 'palatal'     },
                { ipa: 'f',  glyph: 'f',  type: 'fricative'   },
                { ipa: 'v',  glyph: 'v',  type: 'fricative'   },
                { ipa: 's',  glyph: 's',  type: 'fricative'   },
                { ipa: 'z',  glyph: 'z',  type: 'fricative'   },
                { ipa: 'ʃ',  glyph: 'sh', type: 'palatal'     },
                { ipa: 'ʒ',  glyph: 'zh', type: 'palatal'     },
                { ipa: 'h',  glyph: 'h',  type: 'fricative'   },
                { ipa: 'ɣ',  glyph: 'gh', type: 'fricative'   },
                { ipa: 'm',  glyph: 'm',  type: 'nasal'       },
                { ipa: 'n',  glyph: 'n',  type: 'nasal'       },
                { ipa: 'ŋ',  glyph: 'ng', type: 'nasal'       },
                { ipa: 'l',  glyph: 'l',  type: 'approximant' },
                { ipa: 'r',  glyph: 'r',  type: 'approximant' },
                { ipa: 'j',  glyph: 'y',  type: 'palatal'     },
                { ipa: 'q',  glyph: 'q',  type: 'uvular'      },
            ],
            vowels: [
                { ipa: 'a', glyph: 'a', type: 'approximant' },
                { ipa: 'e', glyph: 'e', type: 'approximant' },
                { ipa: 'i', glyph: 'i', type: 'approximant' },
                { ipa: 'ɯ', glyph: 'ı', type: 'approximant' },
                { ipa: 'o', glyph: 'o', type: 'approximant' },
                { ipa: 'u', glyph: 'u', type: 'approximant' },
                { ipa: 'ø', glyph: 'ö', type: 'approximant' },
                { ipa: 'y', glyph: 'ü', type: 'approximant' },
            ],
        }},

    Romance: {
        phonemes: {
            consonants: [
                { ipa: 'p',  glyph: 'p',  type: 'alveolar'    },
                { ipa: 'b',  glyph: 'b',  type: 'alveolar'    },
                { ipa: 't',  glyph: 't',  type: 'alveolar'    },
                { ipa: 'd',  glyph: 'd',  type: 'alveolar'    },
                { ipa: 'k',  glyph: 'k',  type: 'alveolar'    },
                { ipa: 'g',  glyph: 'g',  type: 'alveolar'    },
                { ipa: 'tʃ', glyph: 'ch', type: 'palatal'     },
                { ipa: 'dʒ', glyph: 'j',  type: 'palatal'     },
                { ipa: 'f',  glyph: 'f',  type: 'fricative'   },
                { ipa: 'v',  glyph: 'v',  type: 'fricative'   },
                { ipa: 's',  glyph: 's',  type: 'fricative'   },
                { ipa: 'z',  glyph: 'z',  type: 'fricative'   },
                { ipa: 'ʃ',  glyph: 'sh', type: 'palatal'     },
                { ipa: 'ʒ',  glyph: 'zh', type: 'palatal'     },
                { ipa: 'm',  glyph: 'm',  type: 'nasal'       },
                { ipa: 'n',  glyph: 'n',  type: 'nasal'       },
                { ipa: 'ɲ',  glyph: 'ñ',  type: 'palatal'     },
                { ipa: 'l',  glyph: 'l',  type: 'approximant' },
                { ipa: 'ʎ',  glyph: 'll', type: 'palatal'     },
                { ipa: 'r',  glyph: 'r',  type: 'approximant' },
                { ipa: 'ʀ',  glyph: 'rh', type: 'uvular'      },
                { ipa: 'j',  glyph: 'y',  type: 'palatal'     },
                { ipa: 'w',  glyph: 'w',  type: 'approximant' },
            ],
            vowels: [
                { ipa: 'a', glyph: 'a', type: 'approximant' },
                { ipa: 'e', glyph: 'e', type: 'approximant' },
                { ipa: 'ɛ', glyph: 'è', type: 'approximant' },
                { ipa: 'i', glyph: 'i', type: 'approximant' },
                { ipa: 'o', glyph: 'o', type: 'approximant' },
                { ipa: 'ɔ', glyph: 'ò', type: 'approximant' },
                { ipa: 'u', glyph: 'u', type: 'approximant' },
                { ipa: 'y', glyph: 'ü', type: 'approximant' },
                { ipa: 'ø', glyph: 'œ', type: 'approximant' },
            ],
        }
    },
    Greek: {
        phonemes: {
            consonants: [
                { ipa: 'p',  glyph: 'p',  type: 'alveolar'    },
                { ipa: 'b',  glyph: 'b',  type: 'alveolar'    },
                { ipa: 't',  glyph: 't',  type: 'alveolar'    },
                { ipa: 'd',  glyph: 'd',  type: 'alveolar'    },
                { ipa: 'k',  glyph: 'k',  type: 'alveolar'    },
                { ipa: 'g',  glyph: 'g',  type: 'alveolar'    },
                { ipa: 'f',  glyph: 'f',  type: 'fricative'   },
                { ipa: 'v',  glyph: 'v',  type: 'fricative'   },
                { ipa: 'θ',  glyph: 'th', type: 'fricative'   },
                { ipa: 'ð',  glyph: 'dh', type: 'fricative'   },
                { ipa: 's',  glyph: 's',  type: 'fricative'   },
                { ipa: 'z',  glyph: 'z',  type: 'fricative'   },
                { ipa: 'x',  glyph: 'x',  type: 'fricative'   },
                { ipa: 'ɣ',  glyph: 'gh', type: 'fricative'   },
                { ipa: 'm',  glyph: 'm',  type: 'nasal'       },
                { ipa: 'n',  glyph: 'n',  type: 'nasal'       },
                { ipa: 'ŋ',  glyph: 'ng', type: 'nasal'       },
                { ipa: 'l',  glyph: 'l',  type: 'approximant' },
                { ipa: 'r',  glyph: 'r',  type: 'approximant' },
            ],
            vowels: [
                { ipa: 'a', glyph: 'a', type: 'approximant' },
                { ipa: 'e', glyph: 'e', type: 'approximant' },
                { ipa: 'i', glyph: 'i', type: 'approximant' },
                { ipa: 'o', glyph: 'o', type: 'approximant' },
                { ipa: 'u', glyph: 'u', type: 'approximant' },
            ],
        }
    },
    Slavic: {
        phonemes: {
            consonants: [
                { ipa: 'p',  glyph: 'p',  type: 'alveolar'    },
                { ipa: 'b',  glyph: 'b',  type: 'alveolar'    },
                { ipa: 't',  glyph: 't',  type: 'alveolar'    },
                { ipa: 'd',  glyph: 'd',  type: 'alveolar'    },
                { ipa: 'k',  glyph: 'k',  type: 'alveolar'    },
                { ipa: 'g',  glyph: 'g',  type: 'alveolar'    },
                { ipa: 'ts', glyph: 'c',  type: 'alveolar'    },
                { ipa: 'tʃ', glyph: 'č',  type: 'palatal'     },
                { ipa: 'dʒ', glyph: 'dž', type: 'palatal'     },
                { ipa: 'f',  glyph: 'f',  type: 'fricative'   },
                { ipa: 'v',  glyph: 'v',  type: 'fricative'   },
                { ipa: 's',  glyph: 's',  type: 'fricative'   },
                { ipa: 'z',  glyph: 'z',  type: 'fricative'   },
                { ipa: 'ʃ',  glyph: 'š',  type: 'palatal'     },
                { ipa: 'ʒ',  glyph: 'ž',  type: 'palatal'     },
                { ipa: 'ɕ',  glyph: 'ś',  type: 'palatal'     },
                { ipa: 'x',  glyph: 'h',  type: 'fricative'   },
                { ipa: 'm',  glyph: 'm',  type: 'nasal'       },
                { ipa: 'n',  glyph: 'n',  type: 'nasal'       },
                { ipa: 'ɲ',  glyph: 'ń',  type: 'palatal'     },
                { ipa: 'l',  glyph: 'l',  type: 'approximant' },
                { ipa: 'ʎ',  glyph: 'lj', type: 'palatal'     },
                { ipa: 'r',  glyph: 'r',  type: 'approximant' },
                { ipa: 'j',  glyph: 'j',  type: 'palatal'     },
            ],
            vowels: [
                { ipa: 'a', glyph: 'a', type: 'approximant' },
                { ipa: 'e', glyph: 'e', type: 'approximant' },
                { ipa: 'i', glyph: 'i', type: 'approximant' },
                { ipa: 'o', glyph: 'o', type: 'approximant' },
                { ipa: 'u', glyph: 'u', type: 'approximant' },
                { ipa: 'ɨ', glyph: 'y', type: 'approximant' },
            ],
        },
        typicalSyllableStructures: ['ccv', 'cv', 'cvv', 'vcv', 'cvc', 'v', 'cvcc'],
        typicalOrder: ['Subject', 'Predicate', 'DirectObject', 'IndirectObject']
    },
    Germanic: {
        phonemes: {
            consonants: [
                { ipa: 'p',  glyph: 'p',  type: 'alveolar'    },
                { ipa: 'b',  glyph: 'b',  type: 'alveolar'    },
                { ipa: 't',  glyph: 't',  type: 'alveolar'    },
                { ipa: 'd',  glyph: 'd',  type: 'alveolar'    },
                { ipa: 'k',  glyph: 'k',  type: 'alveolar'    },
                { ipa: 'g',  glyph: 'g',  type: 'alveolar'    },
                { ipa: 'f',  glyph: 'f',  type: 'fricative'   },
                { ipa: 'v',  glyph: 'v',  type: 'fricative'   },
                { ipa: 'θ',  glyph: 'þ',  type: 'fricative'   },
                { ipa: 'ð',  glyph: 'ð',  type: 'fricative'   },
                { ipa: 's',  glyph: 's',  type: 'fricative'   },
                { ipa: 'z',  glyph: 'z',  type: 'fricative'   },
                { ipa: 'ʃ',  glyph: 'sh', type: 'palatal'     },
                { ipa: 'x',  glyph: 'ch', type: 'fricative'   },
                { ipa: 'h',  glyph: 'h',  type: 'fricative'   },
                { ipa: 'm',  glyph: 'm',  type: 'nasal'       },
                { ipa: 'n',  glyph: 'n',  type: 'nasal'       },
                { ipa: 'ŋ',  glyph: 'ng', type: 'nasal'       },
                { ipa: 'l',  glyph: 'l',  type: 'approximant' },
                { ipa: 'r',  glyph: 'r',  type: 'approximant' },
                { ipa: 'j',  glyph: 'j',  type: 'palatal'     },
                { ipa: 'w',  glyph: 'w',  type: 'approximant' },
            ],
            vowels: [
                { ipa: 'a', glyph: 'a', type: 'approximant' },
                { ipa: 'e', glyph: 'e', type: 'approximant' },
                { ipa: 'i', glyph: 'i', type: 'approximant' },
                { ipa: 'o', glyph: 'o', type: 'approximant' },
                { ipa: 'u', glyph: 'u', type: 'approximant' },
                { ipa: 'y', glyph: 'ü', type: 'approximant' },
                { ipa: 'ø', glyph: 'ö', type: 'approximant' },
                { ipa: 'æ', glyph: 'ä', type: 'approximant' },
            ],
        }
    },
    Celtic: {
        phonemes: {
            consonants: [
                { ipa: 'p',  glyph: 'p',  type: 'alveolar'    },
                { ipa: 'b',  glyph: 'b',  type: 'alveolar'    },
                { ipa: 't',  glyph: 't',  type: 'alveolar'    },
                { ipa: 'd',  glyph: 'd',  type: 'alveolar'    },
                { ipa: 'k',  glyph: 'k',  type: 'alveolar'    },
                { ipa: 'g',  glyph: 'g',  type: 'alveolar'    },
                { ipa: 'f',  glyph: 'f',  type: 'fricative'   },
                { ipa: 'v',  glyph: 'v',  type: 'fricative'   },
                { ipa: 's',  glyph: 's',  type: 'fricative'   },
                { ipa: 'ʃ',  glyph: 'sh', type: 'palatal'     },
                { ipa: 'x',  glyph: 'ch', type: 'fricative'   },
                { ipa: 'ɣ',  glyph: 'gh', type: 'fricative'   },
                { ipa: 'h',  glyph: 'h',  type: 'fricative'   },
                { ipa: 'm',  glyph: 'm',  type: 'nasal'       },
                { ipa: 'n',  glyph: 'n',  type: 'nasal'       },
                { ipa: 'ŋ',  glyph: 'ng', type: 'nasal'       },
                { ipa: 'l',  glyph: 'l',  type: 'approximant' },
                { ipa: 'ɬ',  glyph: 'll', type: 'fricative'   },
                { ipa: 'r',  glyph: 'r',  type: 'approximant' },
                { ipa: 'j',  glyph: 'y',  type: 'palatal'     },
                { ipa: 'w',  glyph: 'w',  type: 'approximant' },
            ],
            vowels: [
                { ipa: 'a', glyph: 'a', type: 'approximant' },
                { ipa: 'e', glyph: 'e', type: 'approximant' },
                { ipa: 'i', glyph: 'i', type: 'approximant' },
                { ipa: 'o', glyph: 'o', type: 'approximant' },
                { ipa: 'u', glyph: 'u', type: 'approximant' },
                { ipa: 'ə', glyph: 'e', type: 'approximant' },
            ],
        }
    },

    Sylvan: {
        phonemes: {
            consonants: [
                { ipa: 'p',  glyph: 'p',  type: 'alveolar'    },
                { ipa: 't',  glyph: 't',  type: 'alveolar'    },
                { ipa: 'k',  glyph: 'k',  type: 'alveolar'    },
                { ipa: 'f',  glyph: 'f',  type: 'fricative'   },
                { ipa: 's',  glyph: 's',  type: 'fricative'   },
                { ipa: 'ʃ',  glyph: 'sh', type: 'palatal'     },
                { ipa: 'θ',  glyph: 'th', type: 'fricative'   },
                { ipa: 'ɬ',  glyph: 'lh', type: 'fricative'   },
                { ipa: 'm',  glyph: 'm',  type: 'nasal'       },
                { ipa: 'n',  glyph: 'n',  type: 'nasal'       },
                { ipa: 'ɲ',  glyph: 'ñ',  type: 'palatal'     },
                { ipa: 'l',  glyph: 'l',  type: 'approximant' },
                { ipa: 'ʎ',  glyph: 'ly', type: 'palatal'     },
                { ipa: 'r',  glyph: 'r',  type: 'approximant' },
                { ipa: 'j',  glyph: 'y',  type: 'palatal'     },
                { ipa: 'w',  glyph: 'w',  type: 'approximant' },
            ],
            vowels: [
                { ipa: 'a', glyph: 'a', type: 'approximant' },
                { ipa: 'e', glyph: 'e', type: 'approximant' },
                { ipa: 'ɛ', glyph: 'ë', type: 'approximant' },
                { ipa: 'i', glyph: 'i', type: 'approximant' },
                { ipa: 'o', glyph: 'o', type: 'approximant' },
                { ipa: 'u', glyph: 'u', type: 'approximant' },
                { ipa: 'y', glyph: 'ü', type: 'approximant' },
                { ipa: 'ø', glyph: 'ö', type: 'approximant' },
                { ipa: 'æ', glyph: 'æ', type: 'approximant' },
            ],
        }
    },
}